service: aws-coldstart-ruby25vpc

provider:
  name: aws
  runtime: ruby2.5
  versionFunctions: false
  region: eu-west-1
  tracing: true
  iamRoleStatements:
    - Effect: "Allow" # xray permissions (required)
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

custom:
  apiGatewayCloudWatchSettings:
    metricsEnabled: true

functions:
  outside-128:
    handler: handler.hello
    memorySize: 128
    events:
      - http: GET /outside-128

  outside-512:
    handler: handler.hello
    memorySize: 512
    events:
      - http: GET /outside-512

  outside-1536:
    handler: handler.hello
    memorySize: 1536
    events:
      - http: GET /outside-1536

  inside-128:
    handler: handler.hello
    memorySize: 128
    vpc:
      securityGroupIds:
        - YOUR_ID
      subnetIds:
        - YOUR_ID
    events:
      - http: GET /inside-128

  inside-512:
    handler: handler.hello
    memorySize: 512
    vpc:
      securityGroupIds:
        - YOUR_ID
      subnetIds:
        - YOUR_ID
    events:
      - http: GET /inside-512

  inside-1536:
    handler: handler.hello
    memorySize: 1536
    vpc:
      securityGroupIds:
        - YOUR_ID
      subnetIds:
        - YOUR_ID
    events:
      - http: GET /inside-1536

plugins:
  - serverless-plugin-tracing
  - serverless-api-gateway-cloudwatch-settings
