service: aws-coldstart-ruby25vpc

provider:
  name: aws
  runtime: ruby2.5
  versionFunctions: false
  region: eu-west-1
  tracing: true
  iamRoleStatements:
    - Effect: "Allow" # xray permissions (required)
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

functions:
  memory-128:
    handler: handler.hello
    memorySize: 128
    vpc:
      securityGroupIds:
        - YOUR_ID
      subnetIds:
        - YOUR_ID

  memory-256:
    handler: handler.hello
    memorySize: 256
    vpc:
      securityGroupIds:
        - YOUR_ID
      subnetIds:
        - YOUR_ID

  memory-512:
    handler: handler.hello
    memorySize: 512
    vpc:
      securityGroupIds:
        - YOUR_ID
      subnetIds:
        - YOUR_ID

  memory-1024:
    handler: handler.hello
    memorySize: 1024
    vpc:
      securityGroupIds:
        - YOUR_ID
      subnetIds:
        - YOUR_ID

  memory-2048:
    handler: handler.hello
    memorySize: 2048
    vpc:
      securityGroupIds:
        - YOUR_ID
      subnetIds:
        - YOUR_ID

  memory-3008:
    handler: handler.hello
    memorySize: 3008
    vpc:
      securityGroupIds:
        - YOUR_ID
      subnetIds:
        - YOUR_ID

plugins:
  - serverless-plugin-tracing
