service: aws-coldstart-ruby25

provider:
  name: aws
  runtime: ruby2.5
  versionFunctions: false
  region: eu-west-1

functions:
  memory-128:
    handler: handler.hello
    memorySize: 128

  memory-256:
    handler: handler.hello
    memorySize: 256

  memory-512:
    handler: handler.hello
    memorySize: 512

  memory-1024:
    handler: handler.hello
    memorySize: 1024

  memory-1536:
    handler: handler.hello
    memorySize: 1536
