service: aws-coldstart-ruby25

provider:
  name: aws
  runtime: ruby2.5
  versionFunctions: false
  region: eu-west-1
  tracing: true
  iamRoleStatements:
    - Effect: "Allow" # xray permissions (required)
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

functions:
  memory-128:
    handler: handler.hello
    memorySize: 128

  memory-256:
    handler: handler.hello
    memorySize: 256

  memory-512:
    handler: handler.hello
    memorySize: 512

  memory-1024:
    handler: handler.hello
    memorySize: 1024

  memory-2048:
    handler: handler.hello
    memorySize: 2048

  memory-3008:
    handler: handler.hello
    memorySize: 3008

plugins:
  - serverless-plugin-tracing
